---
title: "Day 10"
date: "2025-07-28"
categories: [Memo]
description: "一步一步，慢慢走"
---

There are always some days when things don't go well.

例如說這兩天，因為下雨停止了跑步，而且之前左腳似乎有肌腱發炎，還沒處理。在工作上可說是一籌莫展。作息中的某個環節如果被移除，其他部分似乎也會逐步崩塌。有時後事情就是如此。

每天都寫文章強度似乎太高，畢竟不是每天都有什麼觀點，計時寫下的文字品質不佳似乎是無可避免的事。但基於先前提到的理由，還是要繼續寫下去。盡量去做到每天規律，去把生活的骨幹給撐住，至少不會全面崩潰。

我想Day 7寫目標的只是一個方向。寫作固然是想要鍛鍊文字技巧，但這個部落格不用侷限於此。這是我處理思緒的地方。寫作也是一種跟外界進行持續連結的嘗試。（這也是為什麼我弄了留言的功能。[^1]）又或者說是一種治療。

[^1]: 目前需要有GitHub帳號才能留言。

持續踏出步伐，儘管只是一小步，也是一種令人穩定的力量。

------------------------------------------------------------------------

關於狀態混亂的時候該如何前進，最近我想起了王泓仁在數值方法講過的Gibbs Sampling。這是一種用在高維度隨機變數抽樣的方法。

設計一個演算法直接對高維度的隨機變數做抽樣相對困難，而Gibbs Sampling的做法是使用條件分配進行抽樣。[^2]給定初始值，先conditional on其他變數，對$x_1$進行抽樣，然後再conditional on 抽出來的$x_1$跟尚未改變的$x_3,...x_k$，對$x_2$進行抽樣。如此持續進行下去。這是一種Markov Chain Monte Carlo，因為蒙地卡羅的性質，整個過程最終會收斂到我們要抽樣的分配上去。

[^2]: 研究室以前的學長最近寫了一篇[網誌](https://jessekelighine.com/metropolis-hastings-algorithm/)介紹Metropolis-Hasting Algorithm 與 Gibbs Sampling.

就當作是過度聯想吧。但生活又何嘗不是如此？我覺得我的思路經常卡住的原因其中之一就是一次考慮太多事情。例如說在分析資料又想到自己應該先去讀什麼文章、想報名英檢又在想應該先去買參考書......。駕馭自己的思緒，某種程度上似乎也是在跟自己說：一步一步來。先假設其他情況不會變了，我們先處理一件事。然後給定新的結果在處理另一件事。或許終究能收斂到一個好的分配。

我現在正在嘗試一種筆記方式：在紙上從中間畫一條線，左邊寫下要決定的事跟選項，右邊放下所有其他給定不變的狀況。如果有什麼成效，可能可以弄成模板跟大家分享。
