---
title: "Day 1"
date: "2025-07-19"
categories: [Memo]
description: "關於數學與經濟模型"
---

昨天，我偶然看到一段由 Lex Fridman 採訪陶哲軒（Terence Tao）的影片。整段訪談長達三個多小時，我只看了其中幾段片段。

即使只是短短幾分鐘的片段，陶哲軒給人的印象就是一位真正的通才。他們談論了各式各樣的主題，而讓我印象最深的是他能以一種高層次的視角來說明複雜的數學問題，並為它們提供脈絡。他語速很快，但表達卻十分清晰。

我不像某些經濟系同學那樣專注於數學，不過偶爾也會為著迷於數學的美感。那種美不只是來自解開難題的快感，而是來自於發現看似無關概念之間隱藏連結的過程，一種統整的美。我很喜歡從事這樣的活動。在教大二學生計量經濟學時，我總是試著以有條理的方式呈現證明，讓它們看起來更清楚，並與其他概念連結起來。對我而言，這就是所謂的「直觀」——不只是自圓其說，更重要的是，你能看見它從何而來。

------------------------------------------------------------------------

不過，作為一位經濟學學生，我對於過度沉迷於尋找「隱含結構」或「潛在連結」這件事，始終抱持著保留態度。我們很容易把這種結構上的優雅誤認為是研究的本質。在經濟學中，我們常常看到不同模型之間有相似之處，或者發現相同的數學技巧可以用來處理看似無關的問題。但這有時其實是種錯覺。或許有人會認為，就像數學在物理學中被用來描述物體的運動，在經濟學中則被用來描述人的選擇行為——但這樣的類比往往只是表面上的。這些相似性，多半來自我們如何建構模型，或者我們是從什麼視角開始分析問題。

舉個例子，在可轉讓效用的家庭配對模型中，我們可以觀察到與福利經濟學第二定理非常相似的結果：模型中的穩定配對概念，對應到某種社會最適條件。這樣的對應確實很有啟發性。但它是否真的揭示了交易與婚配行為之間某種人類行為的共同本質？我並不這麼認為。這種「奇蹟般的結果」，其實是來自我們選擇的工具與設定的目標。我們選擇從一個完美、無摩擦的世界作為分析的起點，但那其實是一種過度簡化，甚至是一種對現實的錯誤描繪。

人的行為是混亂且難以預測的。數學應該是幫助我們理解世界的工具，而不是直接對人類行為的描述。
