project:
  type: website
  output-dir: docs

website:
  title: "HungChiChao"
  draft-mode: unlinked
  site-url: https://hungchichao.github.io
  description: "ChiCHao's Pensieve"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - Favorites.qmd
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/HungChiChao
      - icon: rss
        href: index.xml
  
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css

editor: source



