project:
  type: website
  output-dir: docs

website:
  title: "HungChiChao"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - research.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/HungChiChao
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

