---
title: "Day 12"
date: "2025-07-30"
categories: [Memo]
description: "莊子的美學思想"
---

沒東西寫了，正好上個月645在討論中國的美學，就來研究一下。書讀不通索性直接照抄。

以下文字抄錄自李澤厚與劉綱紀所著《先秦美學史（下）》第七章〈莊子的美學思想〉中「莊子美學的基本特徵」一節。[^1]

[^1]: 其實之所以會去看這本書，單純只是因為它放在我爸的舊書櫃上。

> 莊子學派並不認為人的自由就在於取消和拋棄「物」。相反的，他要「與物為春」（《德充符》），「與萬物有宜而莫知其極」，也就是要支配「物」，使「物」與人相協調、相統一。用莊子學派自己的話說，就是所謂「物物而不物於物」（《山木》），「勝物而不傷」（《應帝王》），「不以物挫志」（《天地》），「不以物害己」（《秋水》）。

> 然而，要怎麼做到「物物而不物於物」，既不拋棄「物」，也不為「物」所支配？... 其中心點就是要把人的生死、壽夭、禍福、窮通、貴賤、得失、成敗等等統統都看成是完全相對的東西，並且是人力所不能左右的，一切聽其自然，「安時而處順，哀樂不能入」， 這樣就可保持內心的平靜和自由。

> 在莊子的哲學中，他的本體論，即關於「道」的學說，是直接爲要求個體的無限和自由的人生哲學做論證。他的本體論主要不在於探究宇宙的本體是什麼、 宇宙是如何生成等問題， 而在論證人類的生存和發展應該向宇宙的本體那樣，達到無限和自由。

> 莊子從道的無限和自由，推出了人的無限和自由，把永恆的大自然無意識、無目的的，卻合乎規律的運動作為人效法的模範。在這裏，莊子認為人有意識，有目的的活動完全可以變成像大自然那樣無意識、無目的的活動，這當然是錯誤的。... 莊子哲學要人消極的順應自然、而不是積極的改造自然，正是竭力要消除人的異化、擺脫物對人的統治的莊子哲學的一個致命的弱點。但他被人稱為滑頭主義的人生哲學，包含個體不應因一時成敗而否定自身存在的思想，把個體生存的價值看得高於人世的一切其他東西。這種思想有其積極方面。

> 在莊子看來，人如果像道那樣行動，他就能達到自由和無限，而自由和無限的達到也就是美。永恆無限、絕對自由的宇宙本體「道」，是一切美所出的根源。莊子論道同時也是論美。他從不離開「道」去講美。他的美學同他的本體論是不能分開的。

> 莊子哲學致力消除人的異化，達到個體的自由和無限，採取的方法既非禁慾主義、也不是理論思辨，而是對生活採取一種**超越利害得失的情感和態度**。這種態度恰好帶有審美的特點。莊子哲學所提倡的人生態度，究其本質來看，正是一種審美的態度。
