---
title: "Day 17"
date: "2025-08-04"
categories: [Memo]
description: "過去的自己2"
---

幾段從廢紙堆中揀出來的文字。對大部分讀者來說應該都沒什麼價值。但我覺得分析自己挺有趣的。

------------------------------------------------------------------------

這是在一張筆記紙上寫的，我完全想不起來自己是什麼場合寫這段話。十五歲生日應該是國三的寒假。

> 昨天剛滿十五歲。 十五歲，介在十八和十二歲之間的一個年齡，人們說是青少年，但我自己，若非把自己完全當成大人，那便是全然地像個小孩。十五歲，一個開朗樂觀、活潑自信，而憂鬱苦悶，充滿迷惘的歲月。我不知道，也無從知曉，十年甚至五十年之的自己，若是再見到這段文字，內心作何感受。或許覺得雲淡風輕卻又顯得刻骨銘心。
>
> 談談我的現狀：十五歲，就讀光明國中，三年級。家裡有爸爸、媽媽、還有弟弟。 朋友，若真的要數，看怎麼數，得出不同的結果來。我真正在乎的，和真正在乎我的，至少有那麼樣的人。我不確定他們是否在乎我，或我不確定是否在乎他們的。朋友的感覺，遇到不同的人都不同體會。每個朋友的意義是不相同的。而我一直嚮往的是契合的知音。我害怕孤獨，在寂寞的時候希望有人陪。

到了二十三歲其實還是在想類似的事，全無長進。

有一件倒是蠻確定的事：高中時期的我有一種抒情（矯情？）的腔調（現在想起來似乎當時試圖模仿《水問》時期簡嫃？希望簡嫃不要生氣。）當然就結果來說不怎麼樣，但因為當時這些文章都沒有給其他人看，也沒有收到什麼反饋，所以這種筆調維持了長一段時間。[^1]

[^1]: 唯一的例外應該是高中的班導師。我在週記簿裡面寫的大概也是這類的文字。依貞每一篇回的得都很認真，真的很不容易。

這段是寫在一張稿紙的背面，我也不確定為什麼當初不寫在正面。就內容推測應該是升高三暑假結束前寫的（2019年夏）。

> 今年夏天，竟也就這麼地結束了。
>
> 七月，我認命的換上學測生的外衣，將參考書和過去的課本在桌上疊好，排放整齊。夏天就這麼悄悄開始了。我開始待閱覽室，一待就是一整天。七月的天氣大致不錯，陽光穿透大片落地窗照進閱覽室，關照每一個或振筆疾書，或昏昏欲睡的考生。而我卻時常望著窗外發呆。學校閱覽室的光線充足，而我竟感覺像是被一座白光建成的囹圄給囚禁了起來。七月酷暑像鞭子，學測是薛西佛斯推著的那塊巨石。
>
> 而八月，竟下起了十天的雨。熱帶氣旋引進豐沛的水氣，傾到在小島上。路上水流成河，人成了魚，卻從未能自在的游。我讀著詩，我的夢也如雨勢般的澎湃洶湧，只是無處可去。今年的夏天哪也不能去。 整座城市在蒸騰，整座島在熱氣中浮動。雨下得再多，仍無從消解他的悶。遠方亞馬遜的森林正在燃燒，彼岸的人民在街頭上戰鬥，而冰島正在為一座冰川的死亡哀悼。
>
> 何以這個夏天竟是如此的不堪？

最近台中也是瘋狂下雨，要不是翻到著個紀錄，以前幾年乾燥的程度，我大概會誤以為以前的台中八月也不下雨。
