---
title: "記與Jimmy問答"
date: "2024-09-20"
categories: [Memo]
description: 個體經濟理論Office Hour
---

（原對話以英文進行，此處以中文重現）

問：老師好，我最近在經濟學原理擔任TA。我們教大一一些基本的經濟觀念，但學生們反應這些模型的結論與他們在現實世界做的決定相悖。我們應該如何回應呢？

答：所有的模型都是簡化過的，所以你遇到模型未必能直接套用在日常生活中的經驗中。例如你問學生「你願意為第三瓶水最高付多少錢」，一般人日常根本不會思考這樣的問題，回答未必真的能看作是他對這個商品滿足程度的衡量。 

問：學生可能會問，如果現實中人不是這樣思考，那這些模型的意義何在？

答：我們的模型必然是一個極度簡化的模型。有人說，模型的功用不過就是在幫我們思考，人做決定時考量的變項有哪些，限制有哪些，互相的關聯是什麼。就想傅利曼說的那樣，我們不要求模型的假設是真的。雖然我們有些人的工作看起來像是物理學那樣，但我們終究不是物理學。他們有很好的工具描述世界運作的基本原理，像是牛頓運動定律，熱力學等等，但經濟學家沒有。

問：那我們關注的是模型的預測力嗎？

答：通常不是。我前陣子遇到做AI的朋友，他對我說「我的模型有一千萬個參數，你們的只有五個，你這個模型怎麼可能fit 呢？」當然，我們經濟學的模型相較之下都是Toy Model ，但是重點在於「你想回答的問題是什麼」。留下問題核心的部分，對其他的部分做簡化，這才是經濟學家要做的事。

問：但我們通常還是會覺得，如果有不只一個模型，那我們仍然可以去探究，哪一個更「接近真實」對吧？

答：這沒有那麽絕對。經濟學家確實會用實證資料檢驗模型。像是在產業組織裡面，雙占市場的經典模型：產量競爭的Cournot模型與價格競爭的Bertrand模型。 大家可能直覺上覺得廠商當然是透過設定價格來競爭，所以Bertrand比較真。但實證的觀察通常發現廠商行為更像是Cournot。事實上，像是美國在打反壟斷的官司，更常參考的也是 Cournot模型。

問：但如果是這樣，我們不就還是以預測力為依歸，而不去關注背後的科學解釋了嗎？

答：並不是。19世紀Cournot提出雙占模型後，Bertrand 認為這完全不make sense, 於是相對地提出另外一個雙占模型，但當時沒有什麼證據，純粹是就模型在爭論。後來隨著實證資料增加，人們發現廠商的行為像是Cournot。於是人們進一步研究Cournot模型。發現在某些條件下，Cournot 與輪流設定產量跟價格的game等價（作者按：我不確定他是不是指 Stackelberg competition) 這就比原本只能設定產量的假設更「符合常理」。科學的進展就是這樣迭代的。基於這些理由，雖然Cournot 看似「假」，但他是廠商行為的一個好的簡化，所以現在人們仍然在使用它。

我：我瞭解了，非常謝謝老師。
