---
title: "解釋"
author: "H.C.C"
date: "2025-02-11"
categories: [NTU]
description: "研究生系列 2"
draft: true
---

下山之後，又回到台北這種濕濕綿綿的雨。

傍晚六點離開辦公室。雨不大，還能保持鞋子的乾燥在路上行走。工作尚未結束，只是不願再留在辦公室。我需要新鮮空氣，哪怕充滿潮濕的氣息。

去連鎖咖啡廳寫計量經濟學的筆記。蠻好笑的，寫給學生的課程筆記也可以作為一種Escapism。

還記得大二的時候，駱班計量經濟的助教表現慘不忍睹。在教室就看著她盯著自己的小抄在黑板上推導Gauss Markov定理推了一節課，自己好像也不確定自己在寫什麼，我自然什麼也沒看懂。

我覺得有一天我要自己來做計量助教。誰知到總算當上計量助教，老闆把助教課取消了。不用站在台上推導Gauss Markov了。所以說其實寫這些note也是一種自作多情。

------------------------------------------------------------------------

$$
\operatorname{Var}(Y) =  \operatorname{Var}(\operatorname{E}[Y\mid X]) + \operatorname{E}[\operatorname{Var}(Y\mid X)].
$$

所有的變化，即能解釋的部分、不能解釋的部分的和。(Law of Total Variance.)

------------------------------------------------------------------------

跟我同研究室的L以前是社工系的。後來雙經濟考上經研所。他說他一直覺得經濟系都是一些不善表達情感的人，像是我。

我想為自己辯駁，但發現他說的沒錯。對我來說，把自己攤開來在別人面前是如此的困難。我猜我在潛意識中有這種想法，是跟其他人談論自己的同時也是在自己的人生辯護。當你訴說自己，確保你的人生、你的抉擇、甚至你的情緒的合理性的舉證責任就在你身上。但對於我為什麼是現在的我，我不擅解釋、無從解釋。

「你的人生不合邏輯」，確實，好似殺人放火一般，十惡不赦的罪。

試著要釐清一切的結局就是無止盡的精神內耗。

------------------------------------------------------------------------

前陣子在家的時候，讀了一點點的「莊子」，有一句話特別引起我的注意。在「養生主」裡，庖丁游刃有餘地將牛之解體之後，「躊躇滿志，善刀而藏之」。如果說我們的精神是刀，在人世間批砍著前進，那莊子的人生建議是要收拾自己的心，不要隨時「與物相刃相靡」。不是所有事情都需要解釋，不是所有事都要想通，就放著吧。

要開學了，還是期待自己的生活會再變得更好一點。希望我能固定去運動，固定找人吃飯，平時多去學校以外的地方走走。
