---
title: "Day 7（關於這個Blog）"
date: "2025-07-25"
categories: [Memo]
description: "42 Days Challenge"
---

親愛的讀者：

我想是時候來談談這個blog的方向是什麼。我平常斷斷續續的會紀錄一些生活上的事，大多數並沒有要給別人看，少數的有。我確實希望自己能夠寫的更認真更勤勞一點，把寫作當作第二專長在經營。不過過去並沒有付諸實現。其中一個問題，是我總是在於應該要寫什麼、怎麼寫上游移不定。

我喜歡閱讀，雖然上大學之後讀書的速度明顯慢下來，但我想應該還是比身邊大部分的人讀得再多一點。詩、散文、小說、傳記、科普書都有。我花了很長的時間才慢慢意識到，我並沒有寫散文的能力。這裡的散文指得是抒情文，文學獎會出現那種。抒情散文貴在真誠。大喇喇的真誠簡單，但無趣；在高超的技巧中保持情感上絕對的真摯，需要天份。我的文字技巧並不適合走這個路線。其中一個原因是，我總好像是要用論理的方式來向別人證明我的情感。我已經發現這在文學上是行不通的，情感早已支離破碎了。

而這次我再度試著開始持續地寫作，目的算是給自己建立一個新的習慣，所以本質上跟跑步的目的是類似的。第一階段的目標，是從上週開始，連續寫42篇部落格。寫作的時間預設是在吃早餐的時候，計時半小時，半小時內寫出什麼就是什麼。（不過有幾天很明顯我在晚上又做了一些調整）

**關於文體**

這個blog的文體是「隨筆」，也就是英文說的Essay，大部分的人都會把法國思想家蒙田當作Essay的始祖。這種文體不太能翻成「散文」（除非我們把散文定義成詩跟小說以外的所有東西）。Essay是談論一件事、一個觀點的短文。因此這42天的訓練，也是在訓練自己在半小時內，盡量把一個「觀點」給講清楚。

**關於內容**

因此雖然是每天更新，但這些隨筆不是日記。我盡量降低記敘文的成分，也避免看起來很像流水帳。我也有考慮過是不是應該更圍繞一個主題來寫（利如介紹某個有趣的經濟學觀念），連寫多天。但我還是決定在前期先把平常堆積在腦中的思緒給倒出來，所以目前這些隨筆多半還是我的生活感觸。

**關於未來**

當然目前出現的文章裡，很多可能都不太能符合我自己設下的標準。有幾篇錯字也沒改（苦笑）。42天後我會再思考該如何處理這42篇隨筆。或許會下架，或許改寫之後再上架，或許就不寫了。誰知道呢？

(不過，因為這是用GitHub Page架設的，所有東西都已經紀錄在GitHub上面，而且因為免費使用所以被迫設定成Public Repository，文章已經永遠留在眾多commit裡面了，除非我刪掉整個repo。)

感謝所有讀到這裡的人。

Chi Chao