---
title: "Day 9"
date: "2025-07-27"
categories: [Memo]
description: "回憶2018"
---

（我思考了一下，原本42篇隨筆的計畫會持續。昨天想要多寫的東西是另外一條線，不限時間。）

回想起2018年——2018年是我的哲學狂熱年。

Day 6的時候寫過，從小腦袋就轉個不停。因此似乎成長過程中的每一個時期都會出現某個讓我著迷的興趣來佔據我的腦袋。國二國三的時候是天文、高一上的時候是法文（可惜現在忘光了）、高一下開始到高二上是哲學。

我的哲學啟蒙書是暢銷著作Micheal Sandel的「正義，一場思辨之旅」。我第一次認識了Mill, Kant, Rawls, Aristoteles。(其實應該還有Milton Friedman 跟 Friedrich von Hayek，但當時我覺得Sandel把他們塑造得像反派角色，抱歉了經濟學家。)那年（高一）寒假，我交給依貞的人社學期報告是寫Thomas Negal的《哲學入門九堂課》，探討懷疑論跟自由意志。 

現在回去看當然覺得有些幼稚和好笑，但當初挺認真的。

台中一中語文資優班的特殊課程其實主要是配合教育部的人文社會計畫，高中一年級下學期的時候有一系列經典導讀課程。課程設計是一個學期有四個session，每個session有一個附近的大學教師來開設微課程，讀一本人文社會的書。我選的四個是政治、哲學、文學跟歷史。（那時候我覺得經濟學就是跟錢有關的東西，沒興趣。）

政治學的老師帶我們讀了柏拉圖的理想國。理想國真的偏無聊，也有可能是老師沒有講到有趣的地方。或許是為了解開「為什麼柏拉圖是西方哲學之父」的疑問，我那時候開始讀各種哲學史的書籍，包括杜蘭威爾的《哲學的故事》。哲學教授帶我們讀笛卡爾的沉思錄，講了四個禮拜只講到「我思考，我存在」。然後剩下的時間都在瞎聊。

我最喜歡的哲學家在一個學期之內從康德換成讓保羅沙特，換成叔本華，換成尼采。當然，看得都是二手資料。（我記得我讀過大概30頁的《作為意志與表象的世界》，因為我爸的書櫃上有，還有大概兩章的《查拉圖斯特拉如是說》，雖然我都記不得他的書名。）

那確實是一段有點瘋狂的時間，我其實一直不確定同學們到底覺得我在幹嘛。當時一個跟我很要好的朋友，時不時要聽我跟他講這些半吊子的讀書心得。終於有一天他不開心了，請我不要在**不適當**的場合一直跟他講這些。我猜那之後我應該是收斂不少。

---

寫這些好像是有些岔題了。

或許只是想追尋，我自己今天的價值觀是在什麼情形下形成的。我曾經相信過什麼又怎麼改變的。

2018年底公投結果出來的時候，高二上的我挺失望的。我當時寫了一篇臉書貼文（已經封存），把支持「進步價值」的人比做理想國「洞穴之寓」中率先走出洞穴看見陽光的賢者，而在洞穴裡的人覺得他瘋了。

現在的我已經不認同我當時的想法。我不認為在民主社會裡有誰可以宣稱自己是「看見陽光」的人，又有誰全然是活在洞穴裡。柏拉圖對民主的懷疑或許有理，但他的理型世界並不更有說服力。

如果我們相信什麼事情是對的，「為你在乎的事而戰，但以**他人能加入行列**的方式實踐。」(美國已故自由派大法官金斯伯格語)。現在的我是這麼相信的。

(寫這篇一不小心就超時了，之後會寫短一點。)