---
title: "In Search of Lost Time "
date: 2024-01-01
categories: [拼貼簿]
description: "Inspried by Marcel Proust"
---

時間與內容無關。

\*\*\*

腸胃炎後的第四天，午餐是吐司配小黃瓜跟玉米。早上把吐司裝進保鮮盒裡，搭上晨間的綠線列車。上次這麼做是在往Downtown Berkeley的列車上。今天的耳機選播李榮浩的「模特」專輯，出道即巔峰，忍不住這樣想著。

胃痛的這幾天，被迫直接面對身體不適的時候，學會了大口呼吸，也許是藏在記憶深處的什麼被喚醒，也許是無計可施。深深的吸氣，吐氣，竟然真的就好過一些。

沒有辦法寫出什麼，如朴作家[^1]一樣令人會心一笑的情節，沒有辦法寫出像是李榮浩出道作那樣的歌詞，想要留下的感覺終究留不住。總還是想要被人關愛，也許對象不應該是朋友圈？也許回去Medium寫作？

[^1]: 朴相映，韓國小說家。著有《大都市的愛情法》、《無人知曉的藝術家之淚和宰桐義大利麵》、《信任的模樣》等書。

不能吃零食，今天的我竟然直接去水果攤買了一顆蘋果。從美國回來之後，似乎就再也沒削過蘋果了。技術一如往常的差，而且沒有專門將蘋果切瓣的刀具，切出來的蘋果歪七扭八。不知道怎麼竟被自己給逗笑了。

在書桌前吃著剛泡玩鹽水的蘋果，想著要為明天去財稅做一點準備還是再閱讀一次朴作家的新書《信任的模樣》。吃完水果還是好餓啊，好想吃雞排（？）從來沒有減肥需求的我經然也被迫面臨「想吃但不能吃」的困擾。（今天至今為止吃了兩片吐司，一碗粥，跟一片蘋果，我是什麼苦行僧嗎）。但吃了那種東西我可能還要再多躺兩天。

還是先閱讀朴作家的書吧。 我有多久沒有在房間看書了？

我不常待在萬隆住處的原因，是因為沒有一張像樣的辦公椅嗎？ 今天從八點就待在家的我，這樣想著。

在社科院的辦公室跟Lab都有裝上輪子，可以滑動的椅子。自己的房間裡是一張普通的木製餐桌椅。想想卻又覺得不對，以我這樣過動的個性，要是在房間裡也擺上一張辦公椅，肯定到處滾來滾去滾到底下鄰居受不了，也罷也罷。還是木頭椅就好。（這可是B還在萬隆的時候我們四個人一起去IKEA搬回來的，我自己組起來的椅子...）

或是是今天確實有點早回家。其實前幾天待在家的時間更長，但主要是躺在床上。莫名奇妙得了腸胃炎直接讓兩個整天報銷，醫生說最近確實流行過一波，難不成是那天去桃機送機[^2]回程的路上沒帶口罩？

[^2]: 一群人去日本玩六天五夜，但出於某些特殊原因竟然有人送機。

不知道為什麼才看了一點點朴作家的書，現在竟然變成在寫作。講到寫作，我最近一直在反省我的文字並不怎麼的「真誠」。我平時就會寫一些簡單紀錄想法的文字，有時候就會想寫長一點。但到底為什麼想寫？事實上對我來說寫作沒有很舒壓，也沒有什麼非寫不可的理由。想到頭來唯一合理的解釋是「討好自己」。確實，就是在討好自己。

\*\*\*

今天我去活大點了碗酸辣湯，外面下以了暴雨，所以我躲進圖書館。躲進圖書館就跑去二樓看《天才的責任》[^3]。一看又花了一個小時。覺得太久了。花太多時間去想哲學問題，從一開始就與維根斯坦背道而馳。不過這本傳記幾乎可以當作理解維根斯坦的入門書。他說，棕皮書（接近於之後出現在哲學研究前一百多節的內容）並不是給其他哲學家看的，而是給跟他具有同樣困惑的人看的。如果單純只是想知道維根斯坦說了什麼而去看哲學研究，那會發現它根本什麼都沒有說。

[^3]: 哲學家維根斯坦的傳記。作者是雷伊．孟克。

還有另一段值得討論的話，在於維根斯坦似乎認為自己的哲學方法就是蘇格拉底的相反。我們很常在接觸哲學的一開始被引導去思考一些日常生活中常見的詞彙，例如「正義」、「善良」的意思，然後被引導而發現一般人並不了解者些詞語的意思，產生許多相互矛盾之處，進而評判一個未經反思的大腦對慨念的理解是混亂的、需要被哲學家加以釐清。但真是這樣嗎？會不會其實只有哲學家不懂什麼是正義？在接觸哲學之前，我們大部分的人在使用正義這個詞時也沒有遇到太多困難，當然每個人指的意思不太一樣，但在與身邊的人溝通上未必有什麼問題。當哲學家跳進來，一切才變得如此讓人困惑。會是這樣嗎？

今天下午算是比較接近在工作的一個日子。但說實話仍舊什麼也沒有做成。我沒有真的理解Collective Labor Supply[^4]，循著找了幾篇文章也沒有細讀。 我自己想像了一個我有興趣的經濟學：How to model? 但並沒有在很多的研究中看到這樣的影子。大部分的人都在測量某種elasticity 。可以說都是的reduced form。How to model is like how to design a board game. As long as you are internally consistent, no one can say you are wrong. However, just as some games are extremely boring, so are some models. 我可以說一直對這件事感到困惑又著迷。但這是一個很小眾的研究興趣嗎？畢竟這本質上不是一個非常科學的問題。但確實是重要的吧，代表說有某種重要無法化約到機制必須保留在模型裡。

[^4]: 家庭經濟學的一種模型。假設家庭成員會互相分工，在家庭內達成帕雷托最優。

\*\*\*

星期六的晚上，研究室的窗戶上還是充滿霧氣。開著冷氣的室內跟潮濕的陽台好像兩個截然不同的世界。不知為何，我把手邊的工作放下了。我想要把事情想清楚。

過去一週極度缺乏生活感。我完全沒有認真想過自己要怎麼樣生活。體現在衣櫃裡塞的完全沒有折的衣服，體現在每一餐吃的漫不經心，也體現在每個決定要提早入睡但還是在床上滑手機滑到眼睛乾澀的晚上。因為白天的事情很多，於是每天就這樣起床上班回家睡覺，也就沒有再思考要怎麼生活。這是個問題，當我在星期五晚上，試著靜下心來，想讓自己休息，卻始終感到很煩躁。很想要一個擁抱，一個就好，讓我能夠好好進入夢鄉。

會覺得對生活不滿意，很大一部份來自於似乎我沒辦法掌控我的心情。我靜不下來，滿腦子想一些關於工作（計量、財稅）或是這個世界亂糟糟的事（川普、柯文哲案、匯率）。我並不真的想要想這些事情。不只是被事情追著跑，更是好像思緒被挾持著沒辦法想清楚。

我覺得現在的我進入一個狀態。我對情緒的感知變得敏感，但我沒有動力去做任何事。開始變得非常需要情緒的照顧。或是說讓自己照顧自己。變得想要得到溫暖。還是害怕孤單。

溫暖是什麼？在愛意的圍繞之下展開新的工作又是什麼樣子？我不想要在像無頭蒼蠅一樣到處亂飛然後用很粗淺的眼光攻擊自己活得不夠好。我不想要攻擊自己活得不夠好，所以我要活得很好。

星期六的晚上給自己一些鼓勵的話。

\*\*\*

一個夢想成為歌手的人，在多久都默默無名之後應該選擇放棄？不可能完全脫離利弊的考量。

或許認清並不是所有事情都能有一個完美的標準。由時就任意的定宜個標準：如果XXX我就放棄。例如：如果申請不到有獎學金的program我就放棄。或是再高一點：如果我申請不到Top 20我就放棄，或是低一點：如果我申請不到任何學校我就放棄。決定這個標準很困難，但同時再怎麼想都還是非常任意，除非擬定一個超寬鬆或超嚴格的標準。

總之，無論從什麼角度看，現在都跟放棄八竿子打不著。比較大的問題是心理問題。改善心理問題本身就是一件改做的事。如果現在不該放棄，那很多煩惱都可以比較單純的被處理。就是：想辦法舒緩、停止這些想法就好了。不需要去理會他們的真實性。但同時，也應該要防止會導致這些想法產生的原因，阻止原因更加重要。

\*\*\*

搬出來住的一個好處，就是可以在晚上的時候，把燈關了，留下一盞昏黃的小桌燈，播一些簡單的音樂。今天播的是Ariana Grande 的Eternal Sunshine Deluxe Version。新加入的幾首歌都非常喜歡。這些歌都有一種很真誠的感覺，能夠輕輕地將你包圍。

有時候換個視角可以看到不同事情，所以我會躺著。租屋處的床很矮，天花板很高，就這樣盯著天花板聽音樂想事情。有時候我在想自己是不是想太多了，好像只要不想太多，事情都能迎刃而解吧，但還沒有想到要怎麼不要想太多（哭笑）。

我有時候也想多紀錄自己平常的生活，但太多的思緒。記錄下來其實也是在將思緒一縷縷梳理開來，否則記下來的都是一些難以追溯的片段。

星期三那天在社科院遇到S學長，索性就走到醉月湖去。那幾天的陽光真的是eternal sunshine ，我們在醉月湖畔看到鴨媽媽跟一群剛孵出來的小鴨，我覺得我可以花一整天看著他們。

那天我順道去校史館買了一組積木（跟樂高很像但不是樂高）總圖。回來花了三天陸陸續續的將他拼好。可惜的是積木竟然沒有把鐘塔做出來，好像少了些什麼東西。我想如果我哪一天又要出國讀書，大概會把他一起帶走吧。有研究室的同學指著總圖前的平台上的樂高人說：「再放個望遠鏡這就是你了」。確實，這幾年來在總圖晃蕩的日子是沒少過，也許拼起來的其實也是我自己的回憶。

Eternal Sunshine 的Deluxe Version 有一個副標題，Brighter Days Ahead. 我有時候會想，在永恆的陽光褪去之後，有什麼理由相信Brighter Days Ahead? 最近聽到今年在川普政府大幅減少預算的狀況下申請國外博士班便當更加艱困，我想我對未來的想像也變得越來越不確定。我該對自己要求些什麼？我能夠期待什麼？再想下去可能又太多了。

這學期修洪俊教的實證賽局分析。洪俊教是去年剛來教書的韓國人，經過許多朋友都認證是系上最帥的男老師。他一直勸我們不要念PhD，說世界上的路還很寬廣。不過上次跟他還有KM去跟來訪的學者出發吃飯，又聊到不做學術要做什麼。我想了一下高中的自己，回答說想當獨立媒體的記者。他們聽完哈哈大笑，說那還是去走學術吧，一樣也能發journal。所以我想我是沒有退路了（苦笑）

所謂的Brighter是什麼意思呢？我其實越來越不確定，說實話我並不期待再次回到美國讀書。有時候我覺得此時此刻或許已經是我人生最幸福的時刻了，我都是修自己有興趣的課，做喜歡的教書工作，跟一群合得來的人生活，應付老師的研究要求。但一切感覺都是在倒數著，我卻還沒找到真正的快樂（或許該說是平靜嗎）。未來似乎並不是一個追尋的目標。當下正在急速地向後退，未來以未曾預告過的速度撲面而來，只怕是要撞得頭破血流。

於是我在想像一種生活，一種在意義結束了之後的生活。世界像是散落一地的樂高，我在廢墟裡面試著拼著自己想要守護的東西，然後等待金黃色的夕陽再次降臨。



\*\*\*

近幾日的陽光很好，萬里無雲，在學校裡散步非常舒服，讓人想起在加州的日子。記憶模糊了，而我也越來越不確定應該要用什麼方式丈量過去和現在，自己的處境是怎麼樣的變化。我在Berkeley的時間並不能稱得上非常開心，但時間越久卻越讓人懷念。而在台灣的日子則是不知道該往哪裡去。

我想像一種處在邊緣的處境。想像一種屬於弱者的敘事，在這裡我用一種承認自己已經認輸離開遊戲之後回過頭來的方式來思考我的人生。一切似乎開始清晰。 時間

跟J在總圖後草坪曬太陽。

那一天下午要去Brown Bag報告。不出所料的焦慮又發作，什麼事也做不了。試圖出去走走晃晃還是一樣。後來J傳了個訊息來說要不要曬太陽。

J是高中的同班同學，上大學之後我們還當過兩年的室友。不過最近因為他要準備考試正在讀書的關係，好像有空能見面的時間更多了一些。

沒想到草坪上陽光把手機曬熱了，曬到不能動，只好挪到比較陰涼的地方。

\*\*\*

Stay with the flow.

星期一來到學校要把論文的附錄給補上。還是經常忍不住要分心。儘管到了這個階段，還是覺得自己有很多是沒有盡到自己的責任。所以很不安。想要讓自己好好放鬆。其實非常的艱難。這一天基本上沒有發生任何有趣的事。我不敢說教書到底是不是讓我快樂。我覺得看到學生的眼神好像有懂會感覺很開心，但是想到他面臨著這麼大的考試而且在學這些沒有用的東西，就覺得一切其實挺沒有意義的（然後擔心自己沒有讓他考過之後也賺不到錢）。然後在感覺緊繃的時候就會很希望自己有戀愛可以談。有時候會想要玩弄一下自己的身體。其實只不過是因為不知道怎麼讓自己內心趨於平靜所做出的無謂舉動。感覺不到生活的flow。

這樣說起來，你必須成承認，這一切就是這麼的無聊。我的人生就是做研究跟教書。這兩件事其實都還蠻無聊的。其實我是對這兩件事都有很高的熱情，但這才是問題所在：因為兩件事大多時候還是偏無聊。而似乎有些不滿就變成看手機了。好像是在那個世界也許、就那麼也許，可以突然找到一種感覺是自己正被關愛著。

不要過度受制於想要被關愛的這種渴望，似乎是必要的。我其實需要高度社交。而且我其實不是不會社交，只是能聊的話題比較侷限，而且對陌生人防備心重。我需要感覺到自己被大家關愛來獲得一些正面的能量。

不要強求。不要刻意去求別人的喜愛。但是可以望人多的地方去，可以更大方一點。或是也許我就是要更接受現在的工作型態。事情還有非常多沒做完。

某種程度上需要記錄每日的思考狀態，畢竟今天狀態不是太好。沒有吃飯，感覺早上上課也提不起勁。覺得自己其實很廢（害怕被看破手腳）又來了，無端的生出一堆麻煩事。我解決事情的方式還是太慢，可能又充滿內耗吧。

\*\*\*

最近的生活稱不上苦，其實就是悶。唯一的起伏大概就是每天在研究室裡會有一些荒誕的事發生。例如今天一夥人在個論上課之前討論到底指導老師消失一週是不是去秘密結婚。有時候又在討論是不是應該在教師節送老師鼻毛剪。研究室裡有一把日式的長刀（塑膠做的），不止一次想要拿刀把這些荒誕的人砍了，然後再自盡。

有時候在思考自己到底想做什麼。首先我完全無法當一個工程師，對於開發工具等之類的事情毫無興趣。也不喜歡處理一些技術細節，所以其實當經濟理論家也不行。

我覺得自己到比較像是某種空想家（原本想說哲學但怕侮辱哲學家），或者應該說是魔法師？奇幻故事裡面最厲害的魔法師通曉世界運作背後最基礎的道理，並能夠運用「道」來施展魔法解決問題。某種程度經濟學也在標榜一種瞭解世界背後運作的道理，並且宣稱這些道理非常有用，跟這些魔法師的目標其實差不多。

但在小說世界裡魔法是真的，在現實中經濟學是假的。現實中並沒有什麼「底層邏輯」或是「洞悉人性的經濟學」這類的東西，看似魔法師只不過是江湖術士。只可惜醒悟的晚了，沒有一技之長只好繼續追求成為一位表面上厲害的魔法師去向更多人販賣魔法。

回家的路上，決定走進誠品逛逛。偶然之間就看到了新銳作家「寺尾哲也」的散文集《努力是癮》。翻了幾頁內心就想起現在的室友B，於是就把這本書買了回去送他。讀著裡面故事人物的人生，想到自己中年之後的樣子。其實我們終究不是天縱英才，而是平凡不過的人。四十歲的時候，如果確實活著的話，應該也是在過極為平凡的人生、煩惱著各種一般人都會煩惱的事情。我自認為還算是相信有「夢想」的人，只是最近也越來越不確定了。人生不都一樣，真有什麼值得追求的「夢」嗎？

回家的路上，經過全家，去買買一送一的翡翠檸檬茶。廣播裡播著曼哈頓練習曲的電影主題曲Lost stars。突然之間心頭一陣翻湧，差點在大庭廣眾之下痛哭失聲…

Just a speck of dust in the galaxy

\*\*\*

事情是這樣的，我喝了一點酒。為什麼呢？因為有人在我的辦公桌上留了一瓶酒。那又是為什麼呢？因為前幾天有一群人在研究室喝酒看煙火，竟然就留下了一瓶酒沒喝完，真掃興。不是，你說，你避開了重點。喔喔，重點，好吧。重點是為什麼我，此時（一個確定的時間點，00:00）此地（一個確定的地點，羅斯福路四段一號臺灣大學社會科學院645室）存在。那又是一段冗長的故事，我想你也未必有興趣，但我知道此事自是無可迴避：

我欠債欠太多了，所以現在正在還債。債主當然就是KM，還有博班的楊學長，我都不敢抬起頭來見他，他想必覺得我是個沒有的草莓族（不是小草）。不錯，一篇文章就然就這麼拖了一個學期沒有進度，我跟老師說我修課忙不過來，唉，老師也真好心，知道人有時必須得做consumption smoothing 。所以現在我就在這啦，時間少的時候欠債，時間多的時候還債，跨期替代，你懂的。

或許你不曾想過，我總覺得夜裡的社科院彷彿一隻碩大的灰白色鯨魚，在名為臺北盆地的內陸海裡漂流。漆黑的海流中明滅著的絢爛的螢光（如果你有看過少年Pi可能有機會知道我在說什麼）同時又覺得這隻鯨魚是個大飯店（夫天地者 萬物之逆旅），我們如魚蝦蜉蝣，寄居於此。（這麼一說，那些拿到tenure 的教授不就成了藤壺？）所以我們不妨就用鯨魚飯店來稱呼吧。

我的研究室在鯨魚飯店的六樓、北側。看得到101，半截。如果說就鯨魚飯店是飯店，那我們的研究室可說就是飯店中的飯店了。上至讀博班的學長，下至大三的學弟，都無不講這裡當作避風港，又或是茫茫大海中唯一的歸宿。所以你看，從上禮拜至今簽到本上已經有九個人簽名（啊忘記給魏珈銘簽了）不過最近會待到這麼晚的人也就只有我一個。上禮拜四，天冷，時間已經過了三更，於是就決定乾脆不回家，在鯨魚飯店住一晚。沒有客房服務但走幾步就有7-11。結論是還是別住好，半夜真快冷死了，要不是有蕭學長（不知道為什麼一位已經讀博班的學長竟然特別來給我們一台電暖爐）的暖爐，大概是活不下去。

這幾天我也反覆思考，為什麼自己做事情這麼慢，一直欠債。有時候坐著想、有時候站著想、有時候一邊踱步一邊忖度，這樣一件重要的問題。這時候你就知道一個人的研究室有什麼迷人之處了。你可以自由的活動、在辦公桌之間踱步、偷偷坐到別人的椅子上滑來滑去、直接把音樂放出來。我總是非常困擾，到底工作的時候要不要聽音樂呢？有時候真需要一些流行樂當作興奮劑或抗憂鬱劑來讓自己繼續做下去，但有時候又會因為聽音樂而分心。跟著哼，或是聽到好喜歡的歌就站起來唱，360度的唱。例如今天就是完全屬於魏如萱的一夜。魏如萱的這張新專輯「珍珠刑」我超愛尤其是下半張抒情歌的部分真的是更上一層樓耶還有之前那張「藏著並不等於遺忘」今天唱了三遍的「星期三或禮拜三」。我媽媽在我小時候一直覺得我是不是有過動症（因為我作業寫到九點半都還寫不完）其實不無道理。不過必須先聲明這些是不可觀察的。雖然你現在知道研究室裡的這位仁兄可能處在某種又唱又跳的混沌疊加狀態，但若你打開研究室的門想要觀測的話，很不幸的，一切就會坍縮到一個人呆呆的坐在電腦桌前面。就是不想讓你看到呵。

所以最近確實是過得比較辛苦一點，在學校待得晚就會想要吃宵夜。我也希望自己是那種朋友隨call隨來就去吃個鐵板燒之類的但可惜就不是。今天去吃了一碗麻油虱目魚湯哎呀天氣冷吃什麼熱的東西都是人間美味。如果是晴天的話我就會晃到總圖前面去數星星（都老朋友了）但天氣不好就只能先回飯店休息。

你說酒是不是喝的有點多，這當然沒有。被放在我桌上的只不過是7-11賣的韓多露荔枝風味燒酒，12度。這點程度是不會醉的，何況有人醉了還會打字嗎？再說，不管怎麼樣你也不用擔這個心，有人說過這些從備忘錄的截圖寫的「我」真的是我嗎？唯一的請求，我會說，也許可以請你不要傳「你還好嗎」的之類的訊息給我。我想你能體諒，一個人如果真醉了亂講話可以推拖說我都不記得，但一個沒有醉的人做出像是喝醉酒的事那可真是沒臉見人了。
