---
title: "Day 2"
date: "2025-07-20"
categories: [Memo]
description: "烏克蘭"
---

我接著看了其他Lex Fridman的訪問節目。我看了今年一月初，他到基輔訪問澤倫斯基，兩個多小時的[訪談](https://youtu.be/u321m25rKXc?si=k3giRr2pY3ZiKLnZ)。

主持人自認為立場是一個中間派，他宣稱此行的目的是要推進雙方停火、談判、協商。他對川普有很強的信心（原因不明），認為川普可以結束這場戰爭。而整場訪問基本上在兩種思維之間激烈來回：「為了停火做出妥協」與「戰鬥直到獲得安全保障」。

主持人不斷詢問「讓步」的可能，但澤倫斯基對於「安全保障」，例如加入北約，始終踩得很死。澤倫斯基清楚的傳達了，身為一個烏克蘭人，暫時向俄羅斯妥協是不能接受的。因為所有俄羅斯的要求都是在讓下一次入侵時烏克蘭毫無抵禦的能力。而烏克蘭人無法、絕對無法，信任普丁的任何承諾。

主持人持始終認為有協商的可能。他提出了一個論點：普丁行動的出發點，終究是為了他心目中俄羅斯人民的福祉。「所有領導人都愛著他的人民」。基於這個假設，他認為協商是可能的，因為長期的戰鬥終究不是俄羅斯人民之福。所以他相信，只要「滿足條件」，普丁會停止這場戰爭。換句話說，我們「必須」相信普丁是理性的，並不全然是因為個人情緒或自己的權力慾望行事。如果普丁目標確實是某種版本的俄羅斯福祉，那談判確實有可能，如果動機全然是個人的，談判如何可能？

澤倫斯基反問，一個讓18歲男孩到前線送死的領導人，一個鎮壓境內其他族群的領導人，如何可能愛著他的人民？沒有烏克蘭人，到現在，能夠相信普丁確實為他的人民著想。普丁向國內隱瞞事實的真相、普丁自己從未到訪前線。澤倫斯基確實認為普丁是瘋狂的，他沒有下限。

唯一能保障烏克蘭的，只有來自歐洲甚至是美國的安全保障。加入北約只是一種保障的形式，以色列沒有加入北約，但比很多北約國家都具有更充足的安全保障。

而他們也談到原諒。有沒有可能，烏克蘭人能原諒普丁？澤倫斯基說出了他心中的未來，就像是納粹德國一樣，普丁需要被咎責，俄羅斯人必須要承認自己的錯誤，並且傳承給下一代，在教育中、文化中，深且反醒。如此，在幾個世代之後，烏克蘭人與俄羅斯人，才有可能再度成為朋友。此時此刻，要求烏克蘭人原諒、放下是不可能的。

---

思考與極權國家的領導人互動，很多時候淪為爭論到底對方心中想要什麼。對於獨裁者的想像，會劇烈影響對於我們該執行什麼樣的行動。我們都希望對方的獨裁者是愛好和平、愛護人民的領導人，那樣我們就不會需要開戰。但我們可以這麼天真嗎？在俄羅斯的例子，不行。

我自己觀察國內政治，我不認為給國民黨人貼上「中共同路人」的標籤是恰當的。不過國民黨人——因為不明原因——普遍相信對岸的領導人是一位理性、愛護人民、愛好和平的領導人。而唯一會受到對方攻擊的可能，就是台灣自己做一個搗蛋鬼去激怒對方。所以自保之道就是討好。

這樣的信任是哪裡來的？我不清楚，但很多台灣人確實抱持這樣的想法。這樣的信任是不是合理的？我不知道，但我無法。


