---
title: "Day 21"
date: "2025-08-13"
categories: [Memo]
description: " 'I' for ideal"
---


I是大我一屆的學長，也是經濟系，也住在鳥不生蛋的男生第四宿舍。

我們是在一門通識課上偶然認識的。

那是一門科普寫作的課，我們要兩人一組，展演一項可以教學的技藝。

老實說我什麼都不會。

因為上學期參加了天文社，我原本想教大家認星星的，但這樣專長在白天哪派得上用場?

剛好坐在我隔壁的就是I，他直接側過身來，問我要不要跟他一組。我問他要教什麼?

他說他想教大家「開鎖」。

於是我們就這樣認識了。

\*\*\*

至於原來同系、同宿舍這件事，是後來有一次，在回城中的交通車上才發現。

I 這個人和我有點像，但又有很多地方不一樣。真要說的話，他大概是「明快」版本的我吧。

每次遇到他，他要不是正在做什麼事，就是正要前往去做什麼事的路上。

他看起來有很多事要做的樣子，但如果我突然想跟他聊天，他還是可以陪我走上一段路。

我常常在猜，他腦袋中是不是把所有待辦事項都像卡片一樣排列，一旦有什麼變化，就只要稍微將卡片抽換一下，行程表就更新了，絲毫不費力的樣子。

我跟他最大的不同，就是我總呈現出迷惘的樣子。有時候我不知道等一下要幹嘛，就會跑進圖書館裡。進圖書館，就會跑去小說櫃看看，又跑去經濟學那櫃看看。雖然架上的書幾乎不會變，但我每次都還是會做這件事，彷彿在尋找什麼。

I也看很多書，但他跟我不一樣，他總是先預約好書，來圖書館只要取書就好。

我在圖書館漫無目的的亂逛時，如果遇到認識的人，問我在這裡做甚麼的時候，我通常只能面露尷尬的表情，支支吾吾地回答一些我也不知道什麼的推託之詞。

(我好討厭那種時候的自己。)

但I幾乎不會面對這種情況，他看似清楚自己每一個行動在幹嘛。

\*\*\*

自從那次分組報告之後，我經常跟他吃飯、和他聊他正在做的事。

實際去觀察他的生活，大概只有一個解釋，就是他真的過得「毫不拖泥帶水」。

(來說說I的人格吧。)

I平常看起來總是獨來獨往的樣子。他很少像其他大學生那樣成群結隊的穿梭在校園裡。

據說他每天的睡眠都很規律。十二點半到一點之間入睡，七點半到八點之間起床。

他總是一個人背著背包出現， 進教室把背包放在固定的位置，打開電腦開始做事。但總是會有人跑去找他講講話，所以人緣還算是不錯。順帶一題，他穿起大衣可真好看。

仔細了解才發現其實他朋友很多，每天晚餐幾乎都有跟人約。嘖嘖。(這學期有一天是跟我。)

他總是能和任何人打交道，不會覺得有任何尷尬，但好像也從來沒跟人稱兄道弟過。

\*\*\*

更讓人覺得厲害的是，I並非過著一成不變的生活。每過一段時間他就會多出一樣新的興趣，來源也都很迷樣。在科普寫作課上我問他什麼時候學了開鎖，他說

「大一的時候忘記鑰匙，偏偏宿舍室友都不在，就這樣被鎖在房間外兩次。第一次就這樣在外面等了一個小時，第二次更慘，因為是連假室友都不在台北，完全無法求救，只好借朋友的宿舍睡。索性自己去研究開鎖，在連假第二天就成功回房間了。」

對於這樣的行動力實在令我佩服不已。（只差沒有像理查費曼一樣，自學開鎖亂開別人的保險箱惡作劇。）

類似的例子俯拾即是。因為喜歡吉他弦震動的聲響就去學吉他；因為想自己架網站就去學寫網頁；剛說要爬山過一個暑假就十幾座百岳(雖然確實有幾座可以一次走完)；從來沒學過日文，因為喜歡上聽日文歌就去把日文考到N4；因為教授說想做荷蘭時期樸社的研究就去學新港文(也太誇張)。超想問他的時間都從哪裡來?

聽說他最近要開始鑽研貝式統計。順帶一提，他還讀過尼采全集。

他有數不清的座右銘(常常聊天聊得高興時就會自己創造出一句）
其中一句是：「已經知道怎麼做的事就快速解決，人生要留給還不會做的事。」

他也不太需要知道在別人眼中自己看起來是什麼樣子，更不會去煩惱諸如「自己的大學生活是不是玫瑰色的」此類問題界定不清、根本無法回答的問題。

我總是在想，像他這樣彷彿自備核動力的幹勁，到底是怎麼做到的？

\*\*\*

接下來的那個學年，我出國交換去了。

交換的過程不能說太順利。

誠然，有些時刻是此生難忘，但default還是那個心神不寧、渾渾噩噩的樣子。

去交換的那間學校，十一座圖書館每座都被我走過好幾遍。當然遇到熟人的機率又更小了。

有時後我會想起I，例如在Instagram上看到他最近又做了什麼新鮮事的時候（例如用Python寫了一個自動交易的程式）。

有時候會想要打電話找他講講話，但因為時差的關係，總不好意思在休息時間打擾他。

在加州也多多少少會遇到個性與I類似的人。當然在我看來，有些美國學生與其說是I的「明快」，更像是對所有事情都沒什麼思考，一股腦地就去做了。

反倒是有認識幾個中國來的交換生，不僅行動力高，對自己的人生也有很多想法。（對他們的國家想法也不少。）

我常在想，也許那樣的性格，才是會在國際的競爭上生存下來的。如果我能像他一樣的話，也許在美國的這段期間，會感到自在不少？

當然我永遠也不會知道。

\*\*\*

回國之後，竟又過了半年，才跟I約吃飯。

許久不見我們都跟對方跟新彼此的近況。我回來繼續在台大讀研究所，而他畢業之後，準備申請國外的研究所（似乎是資料科學？）不過今年的申請結果並不理想。

「可能是話太多時間彈吉他了吧」他笑著說。

我有些訝異，因為他做什麼事情似乎都是很順利。當然客觀上來說我的GPA比他高不少，不過我覺得那只是運氣跟自己對分數的過分執著而已。

我問他說接下來打算做什麼。

在我印象中的第一次，他說他自己也沒有明確的想法。要重新再申請一次也不是不行，但他覺得如果暫時先去工作也不錯。

「我會寫程式又懂一點股票還會Bayesian hierarchical modeling，總不會沒有工作可以做吧？」他半開玩笑的這麼跟我說。

直到現在我都確信，I是那種不管做什麼都能夠成功的人。

\*\*\*

我們都一樣對學習新的事物有很多熱情。不過有一件根本上的差異。

當我做任何事情的時候，都好像是要向別人（或自己心裡的概括化他人）證明些什麼似的，總是迂迴地前進，走走停停，反省著自己是否走了較差的那條路，以及未來要怎麼走上比較好的一條；

而他做的任何一件事都不為了向任何人交代。或許看似不假思索，其實不過是全然地將每一次決定交給當下的自己。

在我眼中，有一個「更好的自己」需要我去達成；而他已經是了，此時此刻，而所謂前進，不過是將自己給充分展開。

我還在想究竟是不是該變成他。

2022-02-04 初稿

2025-08-13 重寫

---

[Day20](https://hungchichao.github.io/posts/0807-day20/) 要自己具備寫作的勇氣，大概是有預感這幾天會慢下來。不是不想寫，但一面想著「我該把事情好好的想清楚」，一面卻又放任自己去接受過量的多巴胺刺激。

這篇短文（小說？）是在我大二寒假寫的。翻看以前儲存在Obsidian的日記偶然又看到。我想當時心裡可能有個I的原型人物，但後來又融合了非常多身邊的人的元素。關於我的部分則都是真的。我想剛好跟最近的一些心境有些契合，就基於原本的架構重新改寫了一下。

最近幾天在聽Justin Bieber的新專輯SWAG。Bieber前陣子在網路上的一些脫序行爲讓很多人懷疑他是不是瘋了，但這張專輯告訴大家他比媒體臆測的還要清醒得多。這張專輯不全然是我喜歡的類型（我比較喜歡R&B的部分），
不過有好幾首歌明確地傳達出「我知道現在的我是一團糟，但我不會逃走，我會留在這裡面對所有需要面對的一切」這樣一種態度。

覺得深具啟發。


