---
title: "Day 14"
date: "2025-08-01"
categories: [Memo]
description: "Writing to Learn"
---

Writing to Learn 是一本William Zinsser所寫，談論寫作的書，出版於1993年。這本書的核心主張是：寫作是「學習」的工具。無論學習任何事物，寫作都可以幫你學得更深、想得更清晰。

我還沒有機會實際找到這本書來讀，只是在網路上大概看了其他人介紹整理。所以在這裡也只是簡單列出我所知道的觀點：

**寫作就是思考的工具**

之所以要在學習時寫作，是因為清晰的寫作與清晰的思考密不可分。要把一件事寫清楚，就得先把一件事想清楚。然而通常只有在我們開始寫，才會發現自己的思維有多不清晰。由此觀之，寫跟思考即是一體。Zinsser甚至鼓勵攻讀數學、物理、化學等學科的學生也要持續以自己所學為題材寫作。我不確定要求數學學生除了會證明之外，還要能用短文「敘述」證明是不是真的有幫助，不過似乎許多數學家（例如Day 1提到的Terence Tao）都有這個能力。我想寫作對經濟學的學生來說，更是被嚴重忽略的一塊。或許之後需要深入探討這個問題。

**寫作是學習的過程**

過去我會把學術寫作當作是學習的「產出」。如果我確實學會了一個概念，我便能夠寫一篇文章介紹這個概念，讓其他人知道我確實理解了。但Zinsser主張寫作就是學習的「過程」。我們應該進行探索性的寫作，而寫作會帶領我們思考。我覺得這方面有些抽象，但我也同意寫作並不應該總是在學習的最後階段出現。如果寫作本身就是思考，那寫作應該從學習的一開始就陪我們到最後。

**關於寫作的建議**

Zinsser列舉了他的一些建議：

1.  模仿好的文章：閱讀你的領域裡的佳作並模仿，這會影響你文字的節奏
2.  先產出草稿，無論品質：正是因為不懂所以才要寫，初稿必然是糟糕的
3.  以清晰為目的修改：裁減冗餘的部分，確保邏輯連貫
4.  以寫作為鏡：讓寫作呈現你實際上的思考邏輯，而非你自以為自己在想什麼

這些建議一樣挺抽象XD

其實在稍微了解Writing to Learn這個概念後，會發現寫作未必需要局限在學習知識上才有幫助。既然寫作與思考是一體，那過生活不也是在思考嗎（至少我是啦）。我想也許最終的目標，是把寫作鑲嵌入生活之中吧。

### References

[Writing to Learn Book Summary: By William Zinsser](https://medium.com/@sabaftsummaries/writing-to-learn-book-summary-by-william-zinsser-04598afd0324)

[Writing to Learn](https://sobrief.com/books/writing-to-learn)
